AWSTemplateFormatVersion: '2010-09-09'
Description: Lab DevOps - 2 EC2 com múltiplas ENIs e EIP.

Parameters:
  ImageId:
    Type: String
    Default: 'ami-0abcdef1234567890' # Substitua pelo ID real da vsbc-image
    Description: AMI ID para as instâncias.

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags: [{Key: Name, Value: Lab-VPC}]

  SubnetPrimaria:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24

  SubnetSecundaria:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24

  # 2. Security Group com as regras pedidas
  MeuSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Regras KSSH, SIP e RTP
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 14022
          ToPort: 14022
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 14140
          ToPort: 14140
          CidrIp: 0.0.0.0/0
        - IpProtocol: udp
          FromPort: 5060
          ToPort: 5060
          CidrIp: 0.0.0.0/0
        - IpProtocol: udp
          FromPort: 30000
          ToPort: 60000
          CidrIp: 0.0.0.0/0

  # 3. Instância 01
  EC2Instancia01:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: c5.large
      ImageId: !Ref ImageId
      NetworkInterfaces:
        - DeviceIndex: '0'
          SubnetId: !Ref SubnetPrimaria
          GroupSet: [!Ref MeuSecurityGroup]
        - DeviceIndex: '1'
          SubnetId: !Ref SubnetSecundaria
          GroupSet: [!Ref MeuSecurityGroup]
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 30

  # 4. EIP para Instância 01 (na interface primária)
  EIP01:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  EIPAssociation01:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt EIP01.AllocationId
      NetworkInterfaceId: !Select [0, !GetAtt EC2Instancia01.NetworkInterfaces]

  # Repetir lógica para EC2Instancia02... (omitido para brevidade)