AWSTemplateFormatVersion: '2010-09-09'
Description: 'vSBC Deploy: 2x vSBC'

Parameters:
  AMIimageID:
    Type: String
    Default: 'ami-0828bad61a1e89d72'
    Description: 'vsbc-w-082025'

  VPCID:
    Type: String
    Default: 'vpc-0bded65f183bc277a'
    Description: 'Flow-MGT-vpc'

  SubnetID:
    Type: String
    Default: 'subnet-0ddc5691dcf373518'
    Description: 'Flow-MGT-subnet-public1'

  SecurityGroupID:
    Type: String
    Default: 'sg-0b3efcbc848058b7c'
    Description: 'Flow-SG'

Resources:
  vSBCTesteCFMaster:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: c5.large
      ImageId: !Ref AMIimageID
      SubnetId: !Ref SubnetID
      SecurityGroupIds: 
        - !Ref SecurityGroupID
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 30
            VolumeType: gp3
      Tags:
        - Key: Name
          Value: vSBC-testeCF-Master

  vSBCTesteCFMasterEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref vSBCTesteCFMaster

  vSBCTesteCFSpare:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: c5.large
      ImageId: !Ref AMIimageID
      SubnetId: !Ref SubnetID
      SecurityGroupIds: 
        - !Ref SecurityGroupID
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 30
            VolumeType: gp3
      Tags:
        - Key: Name
          Value: vSBC-testeCF-Spare

  vSBCTesteCFSpareEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref vSBCTesteCFSpare

Outputs:
  IPPublicoMaster:
    Description: 'IP Fixo do Servidor Master'
    Value: !Ref vSBCTesteCFMasterEIP
  IPPublicoSpare:
    Description: 'IP Fixo do Servidor Spare'
    Value: !Ref vSBCTesteCFSpareEIP